import { Product } from "../types";

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Цемент М500",
    description: "Высококачественный портландцемент для строительных работ",
    price: 450,
    category: "Цемент и бетон",
    image: "https://via.placeholder.com/300x200",
    stock: 100,
  },
  {
    id: "2",
    name: "Кирпич красный",
    description: "Облицовочный кирпич для фасадных работ",
    price: 25,
    category: "Кирпич и блоки",
    image: "https://via.placeholder.com/300x200",
    stock: 500,
  },
  {
    id: "3",
    name: "Брус 150x150",
    description: "Строганный брус из сосны для строительства",
    price: 12000,
    category: "Пиломатериалы",
    image: "https://via.placeholder.com/300x200",
    stock: 50,
  },
  {
    id: "4",
    name: "Металлочерепица",
    description: "Кровельное покрытие с полимерным покрытием",
    price: 850,
    category: "Кровельные материалы",
    image: "https://via.placeholder.com/300x200",
    stock: 200,
  },
  {
    id: "5",
    name: "Штукатурка гипсовая",
    description: "Сухая смесь для внутренних отделочных работ",
    price: 350,
    category: "Отделочные материалы",
    image: "https://via.placeholder.com/300x200",
    stock: 150,
  },
  {
    id: "6",
    name: "Перфоратор",
    description: "Мощный перфоратор для строительных работ",
    price: 12000,
    category: "Инструменты",
    image: "https://via.placeholder.com/300x200",
    stock: 30,
  },
  {
    id: "7",
    name: "Саморезы по дереву",
    description: "Оцинкованные саморезы для крепления деревянных конструкций",
    price: 450,
    category: "Крепежные материалы",
    image: "https://via.placeholder.com/300x200",
    stock: 1000,
  },
];
